url: https://y7kim.github.io
baseurl: ''

# Site settings
title: "Yuanning Li's Research"
email: Yuanning.li@yale.edu
description: "Yuanning Li's Research Page."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: 1062ee
  primary: 1e60d2
  secondary: 3173e3 
  secondary-dark: 000
  
# Team names, titles and social links
people:
- name: Yuanning Li
  pic: Li
  position: Postdoc fellowship
  social:
    - title: google-plus
      url: https://scholar.google.com/citations?user=65ygCIsAAAAJ
    - title: github
      url: https://github.com/yuanning-li/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: google-plus
      url: https://scholar.google.com/citations?user=65ygCIsAAAAJ
    - title: github
      url: https://github.com/yuanning-li/

# Postal address (add as many lines as necessary)
address:
  - line: 165 Prospect Street
  - line: Yale University
  - line: New Haven, CT 06511

# Build settings
markdown: kramdown
permalink: pretty
