url: https://y7kim.github.io
baseurl: ''

# Site settings
title: "Nathan's Research"
email: nathan.whelan@gmail.com
description: "Nathan Whelan's Research Page."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: 1062ee
  primary: 1e60d2
  secondary: 3173e3 
  secondary-dark: 000
  
# Team names, titles and social links
people:
- name: Nathan Whelan
  pic: Whelan
  position: Director
  social:
    - title: twitter
      url: https://twitter.com/polarfire
    - title: google-plus
      url: https://scholar.google.com/citations?hl=en&user=KQ9B0csAAAAJ
    - title: github
      url: https://github.com/NathanWhelan/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: https://twitter.com/polarfire
    - title: google-plus
      url: https://scholar.google.com/citations?hl=en&user=KQ9B0csAAAAJ
    - title: github
      url: https://github.com/NathanWhelan/

# Postal address (add as many lines as necessary)
address:
  - line: 5308 Spring ST
  - line: Warm Springs, GA 31830

# Build settings
markdown: kramdown
permalink: pretty